# Site settings
title: DB Europe
email: 
description: DB Europe > # this means to ignore newlines until "baseurl:"
baseurl: /dbeurope
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
